# @package _global_
config:
  DATA:
    TRAIN:
      DATA_SOURCES: [disk_folder]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [google-imagenet1k-per01]
    TEST:
      DATA_SOURCES: [disk_folder]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [google-imagenet1k-per01]
  OPTIMIZER:
    num_epochs: 60
